[package]
name = "jwt-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
jwt-simple = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid ={ workspace = true }
anyhow = { workspace = true }